server-port=25584
query.port=25584
online-mode=true
enforce-secure-profile=false
view-distance=8
simulation-distance=6
motd=\u00a76Overseer SMP \u00a78| \u00a7fA server ruled by an AI god
max-players=40
difficulty=normal
gamemode=survival
pvp=true
spawn-protection=16
white-list=false
enable-command-block=false
sync-chunk-writes=false
network-compression-threshold=256
